---
title: "R Notebook"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url) # everytime this code is run R will call the internet so we seperate the two steps 

drug_use_html = 
  drug_use_html %>% 
  html_table() %>% 
  first() %>% 
  slice(-1) %>% 
  view

# gives you tables that exist in html
```

## Star Wars
```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")

starwars_titles =
  swm_html %>% 
  html_elements(".lister-item-header a") %>% 
  html_text

swm_revenue =
  swm_html %>% 
  html_elements(".text-muted .ghost~ .text-muted+ span") %>% 
  html_text()

gross_rev_vec = 
  swm_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

runtime_vec = 
  swm_html %>%
  html_elements(".runtime") %>%
  html_text()

```
## Napoleon Dynamite
```{r}
url_d = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url_d)

review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_elements(".review-text-content span") %>%
  html_text()

reviews = 
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )

```

## DOE Water CSV
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")
```

## DOE Water Jason
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```

## Pokemon
```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name
poke[["name"]]
poke$height
poke[["height"]] 
poke$abilities
poke[["abilities"]]
```


